backend:
  name: git-gateway
  accept_roles:
    -admin
    -editor
  branch: master
  commit_messages:
    create: '[skip ci] Create {{collection}} “{{slug}}”'
    update: '[skip ci] Update {{collection}} “{{slug}}”'
    delete: '[skip ci] Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    create: true
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "src/pages/transportation/index.md"
        label: "Transportation"
        name: "transportation"
        fields: 
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "transportation-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}

  - name: "tours"
    label: "Tours"
    folder: "src/pages/tours"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "tour-page"}
      - {label: Title, name: title, widget: string}
      - {label: Image, name: image, widget: image}
      - {label: Description, name: description, widget: string, required: false}
      - {label: Price, name: price, widget: object, fields: [{label: Adults Price, name: adults_price, widget: number, valueType: float}, {label: Children Price, name: children_price, widget: number, valueType: float}, {label: Adults Discount, name: adults_discount, widget: number, valueType: float, required: false}, {label: Children Discount, name: children_discount, widget: number, valueType: float, required: false}, {label: Quintanarroense price, name: q_price, widget: number, valueType: float, required: false}, {label: Transportation price, name: transportation, widget: list, required: false, fields: [{label: Desde, name: from, widget: string}, {label: Precio Adultos, name: adultPrice, widget: number, valueType: float}, {label: Precio niños, name: childPrice, widget: number, valueType: float}]}]}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: Tour type, name: tourType, widget: list }
      - {label: "Horario", name: schedule, widget: string, required: false }
      - {label: "childs", name: "childs", widget: "text", required: false}
      - {label: "Under age", name: "underAge", widget: "text", required: false}
      - {label: "Includes", name: "includes", widget: "text", required: false}
      - {label: "Recommendations", name: "recommendations", widget: "text", required: false}
      - {label: "Info", name: "info", widget: "text", required: false}
      - {label: "Food", name: "food", widget: "boolean", default: false, required: false}
      - {label: "Transportation", name: "transportation", widget: "boolean", default: false, required: false}
      - {label: "Life vest", name: "vest", widget: "boolean", default: false, required: false}
      - {label: "Snorkel", name: "snorkel", widget: "boolean", default: false, required: false}
      
  - name: "circuitos"
    label: "Circuitos"
    folder: "src/pages/circuitos"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "circuit-page"}
      - {label: Title, name: title, widget: string}
      - {label: Image, name: image, widget: image}
      - {label: Description, name: description, widget: string, required: false}
      - {label: Price, name: price, widget: object, fields: [{label: Adults Price, name: adults_price, widget: number, valueType: float}, {label: Children Price, name: children_price, widget: number, valueType: float}, {label: Adults Discount, name: adults_discount, widget: number, valueType: float, required: false}, {label: Children Discount, name: children_discount, widget: number, valueType: float, required: false}, {label: Quintanarroense price, name: q_price, widget: number, valueType: float, required: false}, {label: Transportation price, name: transportation, widget: list, required: false, fields: [{label: Desde, name: from, widget: string}, {label: Precio Adultos, name: adultPrice, widget: number, valueType: float}, {label: Precio niños, name: childPrice, widget: number, valueType: float}]}]}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Horario", name: schedule, widget: string, required: false }
      - {label: "childs", name: "childs", widget: "text", required: false}
      - {label: "Under age", name: "underAge", widget: "text", required: false}
      - {label: "Includes", name: "includes", widget: "text", required: false}
      - {label: "Recommendations", name: "recommendations", widget: "text", required: false}
      - {label: "Info", name: "info", widget: "text", required: false}
      - {label: "Food", name: "food", widget: "boolean", default: false, required: false}
      - {label: "Transportation", name: "transportation", widget: "boolean", default: false, required: false}
      - {label: "Life vest", name: "vest", widget: "boolean", default: false, required: false}
      - {label: "Snorkel", name: "snorkel", widget: "boolean", default: false, required: false}
      
  - name: "destinations"
    label: "Destinations"
    folder: "src/pages/destinations"
    create: true
    fields:
      - {label: Departure name, name: departure, widget: string}
      - {label: Image, name: image, widget: image}
      - {label: Transportation routes, name: routes, widget: list, fields: [{label: Destination, name: destination, widget: relation, collection: "destinations", searchFields: ["departure"], valueField: "departure"}, {label: Price rate, name: price, widget: number}]}

      
